name: test-build

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        go mod tidy
        go build -o go-ul -ldflags "-s -w"
        GOOS=windows GOARCH=amd64 go build -o go-ul.exe -ldflags "-s -w"
        echo "TAG=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
    
    - name: Releas
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: go-ul ${{ env.DATE }}
        tag: ${{ env.VERSION }}
        draft: false
        prerelease: false
        artifacts: |
          go-ul
          go-ul.exe

