name: test-build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        go mod tidy
        go build -o go-ul -ldflags "-s -w"
        GOOS=windows GOARCH=amd64 go build -o go-ul.exe -ldflags "-s -w"
      
    - name: Test Uploade
      run: |
        chmod a+rx go-ul
        go-ul litterbox -f go-ul.exe -o test.txt
